const fs=require('fs');
const path=require('path');
const {AI_PROVIDERS,DEFAULT_PROVIDER,DEFAULT_MODELS,normalizeProvider,providerLabel,modelForProvider,createAiDraft,renderDraftDocx}=require('../engine/ai-recovery');
const {assertUniquePlans}=require('../engine/safety');

function createAiService({safeStorage,localData,ensureAutomationIdle,runNodeScript,lastPayload,acquireLock,releaseLock,runAutomation,userSafeError,compactError,getMainWindow}){
  const {dataDir,jsonPath,readJson,writeJson,loadConfig,loadPlans,savePlans,normalizePlan,appLog}=localData;
  const FREE_PROVIDER_ORDER=['groq','gemini','openrouter'];
  const envNames={groq:['GROQ_API_KEY'],gemini:['GEMINI_API_KEY','GOOGLE_API_KEY'],openrouter:['OPENROUTER_API_KEY'],openai:['OPENAI_API_KEY']};
  function defaultAiSettings(){return {optedIn:false,enabled:false,autoDraftMissing:true,requireApproval:true,provider:DEFAULT_PROVIDER,model:DEFAULT_MODELS[DEFAULT_PROVIDER],models:{...DEFAULT_MODELS},fallbackEnabled:false,planningContext:'',fileNameTemplate:'Week {week2} - Lesson Plans.docx',maxDraftsPerCheck:1,aiSchema:2}}
  function loadAiSettings(){
    const raw=readJson('ai-settings.json',{}),hadPriorSettings=Object.keys(raw||{}).length>0;
    const provider=normalizeProvider(raw.provider||(hadPriorSettings?'openai':DEFAULT_PROVIDER));
    const models={...DEFAULT_MODELS,...(raw.models&&typeof raw.models==='object'?raw.models:{})};
    if(raw.model)models[provider]=String(raw.model);
    const out={...defaultAiSettings(),...raw,provider,models};
    out.optedIn=!!out.optedIn||!!out.enabled;out.enabled=out.optedIn&&!!out.enabled;out.autoDraftMissing=out.autoDraftMissing!==false;out.requireApproval=true;out.fallbackEnabled=!!out.fallbackEnabled;
    for(const id of Object.keys(DEFAULT_MODELS))out.models[id]=modelForProvider(id,out.models[id]);
    out.model=out.models[provider];out.planningContext=String(out.planningContext||'').slice(0,20000);out.fileNameTemplate=String(out.fileNameTemplate||defaultAiSettings().fileNameTemplate).trim().slice(0,180);out.maxDraftsPerCheck=Math.max(1,Math.min(3,Number(out.maxDraftsPerCheck)||1));out.aiSchema=2;return out;
  }
  function draftFileName(settings,week){const n=Number(week);if(!Number.isInteger(n)||n<1||n>52)throw new Error('AI draft week is invalid.');const name=String(settings.fileNameTemplate||defaultAiSettings().fileNameTemplate).replace(/\{week2\}/gi,String(n).padStart(2,'0')).replace(/\{week\}/gi,String(n)).trim();if(!name||/[\\/:*?"<>|]/.test(name)||name==='.'||name==='..')throw new Error('AI lesson-plan filename template contains characters Windows cannot use.');const cfg=loadConfig();let re;try{re=new RegExp(cfg.planTitleRegex,'i')}catch(e){throw new Error(`Drive plan naming rule is invalid: ${e.message}`)}const m=name.match(re);if(!m||Number(m[1])!==n)throw new Error(`AI filename "${name}" does not match the approved Drive plan naming rule for Week ${n}. Update the AI filename format or Drive naming rule.`);return name}
  function aiSecretFile(){return jsonPath('ai-secrets.json')}
  function removeLegacyAiSecretBackup(){try{fs.rmSync(`${aiSecretFile()}.bak`,{force:true})}catch{/* best-effort fallback */}}
  function readSecretRecord(){const file=aiSecretFile();removeLegacyAiSecretBackup();if(!fs.existsSync(file))return {schema:2,providers:{}};let raw;try{raw=JSON.parse(fs.readFileSync(file,'utf8'))}catch{throw new Error('The saved AI connection file could not be read safely. Remove the affected connection and enter its private key again.')}const providers=raw.providers&&typeof raw.providers==='object'?{...raw.providers}:{};if(raw.openaiApiKeyEncrypted&&!providers.openai)providers.openai={apiKeyEncrypted:raw.openaiApiKeyEncrypted};return {schema:2,providers,updatedAt:raw.updatedAt||null}}
  function writeSecretRecord(record){const file=aiSecretFile(),temp=`${file}.${process.pid}.${Date.now()}.tmp`,payload={schema:2,providers:record.providers||{},updatedAt:new Date().toISOString()};const fd=fs.openSync(temp,'w');try{fs.writeFileSync(fd,JSON.stringify(payload,null,2),'utf8');fs.fsyncSync(fd)}finally{fs.closeSync(fd)}try{fs.renameSync(temp,file)}catch(e){if(fs.existsSync(file))fs.unlinkSync(file);fs.renameSync(temp,file)}removeLegacyAiSecretBackup()}
  function environmentSecret(provider){for(const name of envNames[normalizeProvider(provider)]||[]){const value=String(process.env[name]||'').trim();if(value)return value}return ''}
  function writeAiSecret(provider,apiKey){const id=normalizeProvider(provider);if(!safeStorage.isEncryptionAvailable())throw new Error('Windows secure storage is unavailable. The AI private key was not saved.');const record=readSecretRecord();record.providers[id]={apiKeyEncrypted:safeStorage.encryptString(apiKey).toString('base64')};writeSecretRecord(record)}
  function clearAiSecret(provider){const id=normalizeProvider(provider),file=aiSecretFile();if(!fs.existsSync(file)){removeLegacyAiSecretBackup();return}const record=readSecretRecord();delete record.providers[id];if(Object.keys(record.providers).length)writeSecretRecord(record);else{try{fs.rmSync(file,{force:true})}catch{/* best-effort fallback */}removeLegacyAiSecretBackup()}}
  function aiSecretStatus(provider){const id=normalizeProvider(provider),env=environmentSecret(id);if(env)return {provider:id,hasApiKey:true,apiKeySource:'environment',key:env};const record=readSecretRecord(),encoded=String(record.providers?.[id]?.apiKeyEncrypted||'');if(!encoded)return {provider:id,hasApiKey:false,apiKeySource:'none'};if(!safeStorage.isEncryptionAvailable())throw new Error(`Windows secure storage is not available, so the saved ${providerLabel(id)} private key cannot be opened safely.`);try{const key=safeStorage.decryptString(Buffer.from(encoded,'base64')).trim();return {provider:id,hasApiKey:!!key,apiKeySource:key?'saved':'none',key}}catch{throw new Error(`The saved ${providerLabel(id)} private key could not be decrypted on this Windows account. Enter it again in AI Recovery settings.`)}}
  function loadAiSecret(provider){return aiSecretStatus(provider).key||environmentSecret(provider)}
  function hasAiSecret(provider){try{return !!aiSecretStatus(provider).hasApiKey}catch{return false}}
  function connectionStates(){const out={};for(const id of Object.keys(AI_PROVIDERS)){try{const s=aiSecretStatus(id);out[id]={hasApiKey:s.hasApiKey,apiKeySource:s.apiKeySource}}catch{out[id]={hasApiKey:false,apiKeySource:'error'}}}return out}
  function saveAiSettings(input={}){
    ensureAutomationIdle();const current=loadAiSettings(),provider=normalizeProvider(input.provider||current.provider),keyProvider=normalizeProvider(input.connectionProvider||provider),next={...current,...input,provider};delete next.apiKey;delete next.clearApiKey;delete next.connectionProvider;delete next.connections;delete next.hasApiKey;delete next.apiKeySource;
    next.requireApproval=true;next.optedIn=input.optedIn===undefined?!!current.optedIn:!!input.optedIn;next.enabled=next.optedIn&&!!next.enabled;next.autoDraftMissing=next.autoDraftMissing!==false;next.fallbackEnabled=!!next.fallbackEnabled;next.planningContext=String(next.planningContext||'').slice(0,20000);
    if(next.enabled&&next.planningContext.trim().length<20)throw new Error('Before turning on AI recovery, add a short description of what you teach and how your weekly lesson plan should be written.');
    next.models={...DEFAULT_MODELS,...(current.models||{}),...(input.models&&typeof input.models==='object'?input.models:{})};if(Object.prototype.hasOwnProperty.call(input,'model'))next.models[provider]=String(input.model||'');for(const id of Object.keys(DEFAULT_MODELS))next.models[id]=modelForProvider(id,next.models[id]);next.model=next.models[provider];
    next.fileNameTemplate=String(next.fileNameTemplate||defaultAiSettings().fileNameTemplate).trim().slice(0,180);next.maxDraftsPerCheck=Math.max(1,Math.min(3,Number(next.maxDraftsPerCheck)||1));next.aiSchema=2;
    const configuringAi=['provider','fileNameTemplate','planningContext','model','models','maxDraftsPerCheck','apiKey','autoDraftMissing','fallbackEnabled'].some(k=>Object.prototype.hasOwnProperty.call(input,k));if(next.enabled||configuringAi)draftFileName(next,8);
    const apiKey=String(input.apiKey||'').trim();if(input.clearApiKey)clearAiSecret(keyProvider);else if(apiKey){if(apiKey.length<16)throw new Error(`That ${providerLabel(keyProvider)} private key looks incomplete.`);writeAiSecret(keyProvider,apiKey)}
    if(next.enabled&&!hasAiSecret(provider))throw new Error(`Connect ${providerLabel(provider)} before turning on AI missing-plan recovery.`);if(!next.optedIn)next.enabled=false;
    writeJson('ai-settings.json',next);const connections=connectionStates(),secret=connections[provider]||{hasApiKey:false,apiKeySource:'none'};return {...next,connections,hasApiKey:secret.hasApiKey,apiKeySource:secret.apiKeySource};
  }
  function draftsDir(){const d=path.join(dataDir(),'ai-drafts');fs.mkdirSync(d,{recursive:true});return d}
  function loadAiDrafts(){return readJson('ai-drafts.json',[]).filter(x=>x&&x.id&&Number.isInteger(Number(x.week))).slice(-100)}
  function saveAiDrafts(items){writeJson('ai-drafts.json',items.slice(-100));return items}
  function getAiDraft(id){return loadAiDrafts().find(x=>x.id===id)||null}
  function aiPublicState(){const settings=loadAiSettings(),connections=connectionStates(),secret=connections[settings.provider]||{hasApiKey:false,apiKeySource:'none'};return {providers:AI_PROVIDERS,settings:{...settings,connections,hasApiKey:secret.hasApiKey,apiKeySource:secret.apiKeySource},drafts:loadAiDrafts().slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}}
  function draftProviderOrder(settings){const selected=normalizeProvider(settings.provider),order=[selected];if(settings.fallbackEnabled){for(const id of FREE_PROVIDER_ORDER){if(id!==selected&&hasAiSecret(id))order.push(id)}}return order}
  async function createAiDraftForBlocker(blocker,{weekNotes='',force=false}={}){
    const settings=loadAiSettings();if(!settings.enabled||!settings.autoDraftMissing)return null;if(settings.planningContext.trim().length<20)throw new Error('AI recovery needs teacher planning instructions before it can draft a missing plan safely.');
    const week=Number(blocker?.week);if(!Number.isInteger(week))return null;const all=loadAiDrafts(),existing=all.find(d=>Number(d.week)===week&&['ready','uploading','uploaded','submitted'].includes(d.status));if(existing&&!force)return {...existing,reused:true};
    const providers=draftProviderOrder(settings),attempts=[];let result=null,lastError=null;
    for(const provider of providers){
      const apiKey=loadAiSecret(provider);if(!apiKey){if(provider===settings.provider)throw new Error(`AI missing-plan recovery is on, but ${providerLabel(provider)} is not connected.`);continue}
      try{
        result=await createAiDraft({provider,apiKey,model:settings.models?.[provider],week,assignmentTitle:blocker.assignmentTitle||`Week ${week} - Lesson Plans`,dueText:blocker.dueText||'',cardText:blocker.cardText||'',planningContext:settings.planningContext,weekNotes});
        attempts.push({provider,status:'success'});break;
      }catch(e){
        lastError=e;attempts.push({provider,status:'failed',retryable:!!e.aiProviderRetryable,message:compactError(e)});appLog(`AI recovery Week ${week}: ${providerLabel(provider)} failed safely: ${compactError(e)}`);
        if(!settings.fallbackEnabled||!e.aiProviderRetryable)throw e;
      }
    }
    if(!result)throw lastError||new Error('No connected AI service could create the lesson-plan draft.');
    const filename=draftFileName(settings,week);result.plan.title=filename.replace(/\.docx$/i,'');result.plan.weekNumber=week;const localFile=path.join(draftsDir(),`AI-DRAFT-${filename}`);renderDraftDocx(result.plan,localFile);
    const record={id:`week-${week}-${Date.now()}`,week,filename,localFile,status:'ready',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),assignmentTitle:blocker.assignmentTitle||'',dueText:blocker.dueText||'',cardText:blocker.cardText||'',weekNotes:String(weekNotes||''),provider:result.provider||settings.provider,providerLabel:providerLabel(result.provider||settings.provider),providerAttempts:attempts,model:result.model,responseId:result.responseId||null,plan:result.plan};
    const next=all.filter(d=>!(force&&Number(d.week)===week&&d.status==='ready'));next.push(record);saveAiDrafts(next);appLog(`AI recovery created a local Week ${week} draft with ${record.providerLabel}. It was not uploaded or submitted.`);const win=getMainWindow();if(win&&!win.isDestroyed())win.webContents.send('ai-draft-ready',{id:record.id,week});return {...record,reused:false};
  }
  async function processMissingPlanRecovery(result){const settings=loadAiSettings();if(!settings.enabled||!settings.autoDraftMissing||!result)return [];const missing=(result.blockers||[]).filter(b=>b?.type==='MISSING_PLAN');if(!missing.length)return [];const created=[],pending=[],failures=[],seen=new Set();for(const b of missing){const week=Number(b.week);if(!Number.isInteger(week)||seen.has(week))continue;seen.add(week);try{const d=await createAiDraftForBlocker(b);if(d&&d.status==='ready'){if(d.reused)pending.push(d);else created.push(d)}}catch(e){const message=compactError(e);failures.push({week,message});appLog(`AI recovery Week ${week} failed safely: ${message}`)}if(created.length>=settings.maxDraftsPerCheck)break}if(created.length){result.aiDraftsCreated=created.map(d=>({id:d.id,week:d.week}));result.message=`Week ${created.map(d=>d.week).join(', ')} was missing, so AI created a local draft for teacher review. Nothing was uploaded or submitted.`}else if(pending.length){result.aiDraftsPending=pending.map(d=>({id:d.id,week:d.week}));result.message=`Week ${pending.map(d=>d.week).join(', ')} is still missing, and its AI draft is already waiting for teacher review. Nothing was uploaded or submitted.`}else if(failures.length){result.aiDraftFailures=failures;result.message=`A lesson plan is missing, and AI drafting also needs attention: ${failures.map(x=>`Week ${x.week}: ${x.message}`).join('; ')}`}return created}
  async function scanDrivePlansRaw(){const out=await runNodeScript('scan-drive-folder.js',[],false);const plans=lastPayload(out,'drive-plans');return Array.isArray(plans)?plans:[]}
  async function scanAndSaveDrivePlans(){const discovered=await scanDrivePlansRaw();assertUniquePlans(discovered);const existing=loadPlans(),priorDrive=new Map(existing.filter(p=>p.source==='drive-folder').map(p=>[Number(p.week),p])),manual=existing.filter(p=>p.source!=='drive-folder');const synced=discovered.map(p=>normalizePlan({...p,weekOf:priorDrive.get(Number(p.week))?.weekOf||p.weekOf||'',source:'drive-folder'}));return savePlans([...manual,...synced],{trustedDriveSync:true})}
  async function approveAiDraft(id){ensureAutomationIdle();const approvalLock=acquireLock('AI draft approval/upload');let lockHeld=true,staged='';try{const draft=getAiDraft(id);if(!draft)throw new Error('That AI lesson-plan draft no longer exists.');if(draft.status!=='ready')throw new Error('That AI draft is not waiting for approval.');const settings=loadAiSettings(),finalName=draftFileName(settings,draft.week);if(finalName!==draft.filename)throw new Error('The approved filename settings changed after this draft was created. Regenerate the draft first.');let existing=[];try{existing=await scanDrivePlansRaw()}catch(e){if(!/No lesson-plan files matched/i.test(String(e.message||'')))throw e}const hit=existing.find(p=>Number(p.week)===Number(draft.week));if(hit)throw new Error(`Week ${draft.week} now already has a plan in the approved Drive folder. Nothing was uploaded. Review the existing plan or dismiss this AI draft.`);const stagingDir=path.join(draftsDir(),'approved-upload');fs.mkdirSync(stagingDir,{recursive:true});staged=path.join(stagingDir,finalName);fs.copyFileSync(draft.localFile,staged);const all=loadAiDrafts(),rec=all.find(x=>x.id===id);rec.status='uploading';rec.updatedAt=new Date().toISOString();saveAiDrafts(all);try{await runNodeScript('upload-draft-plan.js',[staged,String(draft.week)]);const plans=await scanAndSaveDrivePlans(),plan=plans.find(p=>Number(p.week)===Number(draft.week));if(!plan)throw new Error(`Google Drive accepted the upload, but Week ${draft.week} could not be verified in the approved folder. Nothing will be submitted until the folder scan can verify it.`);const nowAll=loadAiDrafts(),nowRec=nowAll.find(x=>x.id===id);Object.assign(nowRec,{status:'uploaded',updatedAt:new Date().toISOString(),approvedAt:new Date().toISOString(),planUrl:plan.url});saveAiDrafts(nowAll);appLog(`AI recovery Week ${draft.week}: teacher approved draft and Drive upload was verified.`);releaseLock(approvalLock);lockHeld=false;let submission=null,submitError=null;const cfg=loadConfig();if(!cfg.dryRun){try{submission=await runAutomation(false);if(submission?.result?.submitted>0){const finalAll=loadAiDrafts(),finalRec=finalAll.find(x=>x.id===id);if(finalRec){finalRec.status='submitted';finalRec.submittedAt=new Date().toISOString();finalRec.updatedAt=finalRec.submittedAt;saveAiDrafts(finalAll)}}}catch(e){const info=userSafeError('automation:run',e?.runResult?.message||e);submitError=`CATI_UI|${info.code}|${info.message}`;appLog(`AI recovery Week ${draft.week}: upload succeeded but immediate submission did not complete: ${compactError(e)}`)}}return {uploaded:true,plan,submission:submission?.result||null,submitError,draft:getAiDraft(id)}}catch(e){const failed=loadAiDrafts(),f=failed.find(x=>x.id===id);if(f){f.status='ready';f.updatedAt=new Date().toISOString();f.lastError=compactError(e);saveAiDrafts(failed)}throw e}}finally{if(lockHeld)releaseLock(approvalLock);if(staged){try{fs.unlinkSync(staged)}catch{/* best-effort fallback */}}}}
  return {loadAiSettings,saveAiSettings,aiPublicState,draftsDir,loadAiDrafts,saveAiDrafts,getAiDraft,createAiDraftForBlocker,processMissingPlanRecovery,scanDrivePlansRaw,scanAndSaveDrivePlans,approveAiDraft};
}
module.exports={createAiService};
